<?php

/**
 * @file
 *
 */

/**
 * Implements hook_install().
 */
function field_permissions_dev_install() {
  include_once DRUPAL_ROOT . '/profiles/minimal/minimal.install';

  // Enable the admin theme.
  db_update('system')
    ->fields(array('status' => 1))
    ->condition('type', 'theme')
    ->condition('name', 'ember')
    ->execute();
  variable_set('admin_theme', 'ember');
  variable_set('theme_default', 'ember');
  variable_set('node_admin_theme', '1');

  minimal_install();
}
